# define some aliases
Alt     = AltLeft
AltGr   = AltRight
Win     = Meta
Command = Meta

# immediately forward common modifier keys (also used as mouse modifiers)
@forward-modifiers Shift Control Alt

CapsLock >>
CapsLock{Z}               >> Alt 
CapsLock{V} >> Shift 
CapsLock{C}               >> Control 
CapsLock{A}               >> Alt   # also map A because of S/D rollover map CapsLock-I/J/K/L to cursor keys... 

CapsLock{J}               >> ArrowDown
CapsLock{K}               >> ArrowUp
CapsLock{H}               >> ArrowLeft
CapsLock{L}               >> ArrowRight
CapsLock{N}               >> PageUp
CapsLock{M}               >> PageDown

Control AltRight >> Escape
# # define a virtual "boss" key, which can be toggled using the scroll-lock key
# # when the boss key is "pressed", the keyboard should be intuitively useable
# Boss = Virtual1
# ScrollLock >> Boss
# Boss{Any} >> Any

# # map Capslock to Backspace
# Control{CapsLock} >> CapsLock
# CapsLock          >> Backspace

# # define an additional modifier "Ext" (angular bracket key on some keyboards)
# Ext = IntlBackslash

# # the Ext modifier alone should have no effect
# Ext >>

# # map Ext-S/D/F to Alt/Shift/Control
# Ext{S}               >> Alt
# Ext{D}               >> Shift
# Ext{F}               >> Control
# Ext{A}               >> Alt   # also map A because of S/D rollover

# # map Ext-I/J/K/L to cursor keys...
# Ext{J}               >> ArrowDown
# Ext{K}               >> ArrowUp
# Ext{H}               >> ArrowLeft
# Ext{L}               >> ArrowRight
# Ext{N}               >> PageUp
# Ext{M}               >> PageDown
